from typing import Any

class Storage:
    """File storage facade."""

    def add_driver(name: str, driver: str): ...
    def set_configuration(config: dict) -> "Storage": ...
    def get_driver(name: str = None) -> Any: ...
    def get_config_options(name: str = None) -> dict: ...
    def disk(name: str = "default") -> Any:
        """Get the file manager instance for the given disk name."""
        ...
    # TODO: add typing contract of storage driver
    def build(driver_name: str, options: dict = {}) -> Any:
        """Get a storage driver instance based on the given driver built on the fly with the given options."""
        ...
    def get_path(path: str) -> str:
        """Get absolute path to given path for default driver."""
        ...
    def get_name(path: str, alias: str = None): ...
    def size(path: str) -> int: ...
    def human_size(path: str) -> str: ...
    def last_modified(path: str) -> float: ...
    def put(path: str, content: str | bytes | bytearray) -> bool: ...
    def put_file(path: str, file: File | UploadedFile): ...
    def put_file_as(
        path: str, file: UploadedFile, name: str = "", filename: str = ""
    ): ...
    def get(path: str) -> "str|None": ...
    def exists(path: str) -> bool: ...
    def missing(path: str) -> bool: ...
    def stream(path: str) -> FileStream: ...
    def copy(src: str, destination: str) -> bool: ...
    def move(src: str, destination: str) -> bool: ...
    def prepend(path: str, content: str) -> bool: ...
    def append(path: str, content: str) -> bool: ...
    def delete(path: str) -> bool: ...
    def make_directory(
        directory_path: str, mode="755", force=False, recursive=True
    ): ...
    def delete_directory(directory_path: str, preserve: bool = False) -> bool: ...
    def files(directory_path: str = "") -> "Collection[File]": ...
    def all_files(directory_path: str = "") -> "Collection[File]": ...
    def directories(directory_path: str = "") -> "Collection[str]": ...
    def get_url(path: str): ...

    # TODO:
    def response(file_path, name=None, headers={}, disposition="inline"): ...

    # TODO:
    def download(file_path, name=None, headers={}): ...
